'use client';

import { Button } from './ui/button.tsx';
import { Input } from './ui/input.tsx';
import { Label } from './ui/label.tsx';
import type { UINode, ConstantDefinition } from '@molstar/state-builder';
import { getValidChildren, isTerminalKind, countSubtreeNodes, deepCopyNode, isAutoGeneratedRef, generateDefaultRef } from '@molstar/state-builder';
import { ConfirmDialog } from './ui/confirm-dialog.tsx';
import { detectCompositeSequence } from '@molstar/state-builder/types/composite-sequences';
import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-react';
import { useEffect, useState } from 'react';
import { cn } from './lib/utils.ts';
import { TreeLines } from './components/TreeLines.tsx';
import { OperationActions } from './components/OperationActions.tsx';
import { KindSelect } from './components/KindSelect.tsx';
import { CompositeRow } from './CompositeRow.tsx';
import { PrimitivesRow } from './PrimitivesRow.tsx';
import {
  StructureFields,
  ComponentFields,
  RepresentationFields,
  ColorFields,
  TransformFields,
  LabelFields,
  OpacityFields,
  CameraFields,
  FocusFields,
  CanvasFields,
  TooltipFields,
  VolumeFields,
  VolumeRepresentationFields,
  ColorFromUriFields,
  ColorFromSourceFields,
  LabelFromUriFields,
  LabelFromSourceFields,
  TooltipFromUriFields,
  TooltipFromSourceFields,
  ComponentFromUriFields,
  ComponentFromSourceFields,
} from './components/fields/index.ts';

interface OperationRowProps {
  node: UINode;
  onUpdate: (updates: Partial<UINode>) => void;
  onRemove: () => void;
  onAddChild?: () => void;
  onAddTemplateChildren?: (nodes: UINode[]) => void;
  onCopy?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  depth?: number;
  isLast?: boolean;
  isFirst?: boolean;
  availableConstants?: ConstantDefinition[];
  allowedKinds?: readonly MVSKind[];
  allNodes?: UINode[];
}

export function OperationRow({
  node,
  onUpdate,
  onRemove,
  onAddChild,
  onAddTemplateChildren,
  onCopy,
  onMoveUp,
  onMoveDown,
  depth = 0,
  isLast = false,
  isFirst = false,
  availableConstants = [],
  allowedKinds,
  allNodes = [],
}: OperationRowProps) {
  const [isExpanded, setIsExpanded] = useState(true);
  const [customOpen, setCustomOpen] = useState(false);
  const [customInput, setCustomInput] = useState(() =>
    node.custom != null ? JSON.stringify(node.custom, null, 2) : ''
  );
  const [customError, setCustomError] = useState('');

  useEffect(() => {
    setCustomInput(node.custom != null ? JSON.stringify(node.custom, null, 2) : '');
  }, [node.custom]);

  const [pendingAction, setPendingAction] = useState<{
    type: 'delete' | 'kindChange';
    newKind?: MVSKind;
  } | null>(null);

  const childCount = node.children?.length || 0;
  const subtreeCount = countSubtreeNodes(node);

  // Check if this node is the root of a composite sequence
  const compositeMatch = detectCompositeSequence(node);

  if (compositeMatch) {
    return (
      <CompositeRow
        sequence={compositeMatch.sequence}
        rootNode={node}
        exitNode={compositeMatch.exitNode}
        onUpdate={onUpdate}
        onRemove={onRemove}
        onCopy={onCopy}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        depth={depth}
        isFirst={isFirst}
        isLast={isLast}
        availableConstants={availableConstants}
        allowedKinds={allowedKinds}
        allNodes={allNodes}
      />
    );
  }

  if (node.kind === 'primitives') {
    return (
      <PrimitivesRow
        node={node}
        onUpdate={onUpdate}
        onRemove={onRemove}
        onCopy={onCopy}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        depth={depth}
        isFirst={isFirst}
        isLast={isLast}
        availableConstants={availableConstants}
        allowedKinds={allowedKinds}
        allNodes={allNodes}
      />
    );
  }

  const shouldAutoRef = !node.ref || isAutoGeneratedRef(node.ref);

  const handleKindChange = (kind: MVSKind) => {
    const ref = shouldAutoRef ? generateDefaultRef(kind, allNodes) : undefined;
    if (childCount > 0) {
      setPendingAction({ type: 'kindChange', newKind: kind });
    } else {
      onUpdate({ kind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
  };

  const handleRemove = () => {
    if (childCount > 0) {
      setPendingAction({ type: 'delete' });
    } else {
      onRemove();
    }
  };

  const handleConfirmAction = () => {
    if (!pendingAction) return;

    if (pendingAction.type === 'delete') {
      onRemove();
    } else if (pendingAction.type === 'kindChange' && pendingAction.newKind) {
      const ref = shouldAutoRef ? generateDefaultRef(pendingAction.newKind, allNodes) : undefined;
      onUpdate({ kind: pendingAction.newKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }

    setPendingAction(null);
  };

  const handleCompositeSelect = (compositeNode: UINode) => {
    // Replace current node with the composite structure
    onUpdate({
      kind: compositeNode.kind,
      params: compositeNode.params,
      children: compositeNode.children,
      ref: compositeNode.ref,
    });
  };

  const handleParamsChange = (params: Record<string, unknown>) => {
    onUpdate({ params });
  };

  const handleCustomChange = (custom: Record<string, unknown> | undefined) => {
    onUpdate({ custom });
  };

  const handleCustomInputChange = (v: string) => {
    setCustomInput(v);
    if (!v.trim()) {
      setCustomError('');
      handleCustomChange(undefined);
      return;
    }
    try {
      const parsed = JSON.parse(v);
      setCustomError('');
      handleCustomChange(parsed);
    } catch {
      setCustomError('Invalid JSON');
    }
  };

  const handleRefChange = (value: string) => {
    onUpdate({ ref: value });
  };

  const canHaveChildren = !isTerminalKind(node.kind);
  const validChildKinds = getValidChildren(node.kind);

  const renderDynamicFields = () => {
    if (!node.params) {
      return null;
    }

    switch (node.kind) {
      case 'structure':
        return <StructureFields params={node.params} onChange={handleParamsChange} />;

      case 'component':
        return <ComponentFields params={node.params} onChange={handleParamsChange} />;

      case 'representation':
        return <RepresentationFields params={node.params} onChange={handleParamsChange} />;

      case 'color':
        return (
          <ColorFields
            params={node.params}
            custom={node.custom}
            availableConstants={availableConstants}
            onApply={(newParams, newCustom) => onUpdate({ params: newParams, custom: newCustom })}
          />
        );

      case 'transform':
        return <TransformFields params={node.params} onChange={handleParamsChange} />;

      case 'label':
        return <LabelFields params={node.params} onChange={handleParamsChange} />;

      case 'opacity':
        return <OpacityFields params={node.params} onChange={handleParamsChange} />;

      case 'camera':
        return <CameraFields params={node.params} onChange={handleParamsChange} />;

      case 'focus':
        return <FocusFields params={node.params} onChange={handleParamsChange} />;

      case 'canvas':
        return <CanvasFields params={node.params} onChange={handleParamsChange} />;

      case 'tooltip':
        return <TooltipFields params={node.params} onChange={handleParamsChange} />;

      case 'volume':
        return <VolumeFields params={node.params} onChange={handleParamsChange} />;

      case 'volume_representation':
        return <VolumeRepresentationFields params={node.params} onChange={handleParamsChange} />;

      case 'color_from_uri':
        return <ColorFromUriFields params={node.params} onChange={handleParamsChange} />;

      case 'color_from_source':
        return <ColorFromSourceFields params={node.params} onChange={handleParamsChange} />;

      case 'label_from_uri':
        return <LabelFromUriFields params={node.params} onChange={handleParamsChange} />;

      case 'label_from_source':
        return <LabelFromSourceFields params={node.params} onChange={handleParamsChange} />;

      case 'tooltip_from_uri':
        return <TooltipFromUriFields params={node.params} onChange={handleParamsChange} />;

      case 'tooltip_from_source':
        return <TooltipFromSourceFields params={node.params} onChange={handleParamsChange} />;

      case 'component_from_uri':
        return <ComponentFromUriFields params={node.params} onChange={handleParamsChange} />;

      case 'component_from_source':
        return <ComponentFromSourceFields params={node.params} onChange={handleParamsChange} />;

      default:
        return null;
    }
  };

  return (
    <div className='relative' style={{ marginLeft: depth > 0 ? '20px' : '0' }}>
      <TreeLines depth={depth} isLast={isLast} />

      <div className='border rounded-md p-2 bg-card'>
        <div className='flex gap-2 items-end'>
          {canHaveChildren && (
            <Button
              variant='ghost'
              size='sm'
              onClick={() => setIsExpanded(!isExpanded)}
              className='h-8 w-8 p-0'
              title={isExpanded ? 'Collapse' : 'Expand'}
            >
              {isExpanded ? <ChevronDownIcon className='size-4' /> : <ChevronRightIcon className='size-4' />}
            </Button>
          )}

          <KindSelect
            value={node.kind}
            onChange={handleKindChange}
            onCompositeSelect={handleCompositeSelect}
            allowedKinds={allowedKinds}
          />

          {renderDynamicFields()}

          <div className='w-24'>
            <Label className='text-xs'>Ref</Label>
            <Input
              className='h-8 text-sm'
              placeholder='name'
              value={node.ref || ''}
              onChange={(e) => handleRefChange(e.target.value)}
              title='Reference name to use this operation later'
            />
          </div>

          <OperationActions
            canHaveChildren={canHaveChildren}
            isFirst={isFirst}
            isLast={isLast}
            parentKind={node.kind}
            onMoveUp={onMoveUp}
            onMoveDown={onMoveDown}
            onAddChild={onAddChild}
            onAddTemplateChildren={onAddTemplateChildren}
            onCopy={onCopy}
            onRemove={handleRemove}
          />
        </div>

        {/* Custom Data expander */}
        <div className='mt-1'>
          <button
            type='button'
            className='flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors'
            onClick={() => setCustomOpen((o) => !o)}
          >
            <ChevronRightIcon className={cn('size-3 transition-transform', customOpen && 'rotate-90')} />
            Custom data
            {node.custom != null && (
              <span className='ml-1 size-1.5 rounded-full bg-primary inline-block' />
            )}
          </button>
          {customOpen && (
            <div className='mt-1'>
              <textarea
                className='w-full text-xs font-mono border rounded-md p-2 min-h-[80px] resize-y bg-background'
                placeholder='{ "key": "value" }'
                value={customInput}
                onChange={(e) => handleCustomInputChange(e.target.value)}
                spellCheck={false}
              />
              {customError && <p className='text-xs text-destructive mt-1'>{customError}</p>}
            </div>
          )}
        </div>
      </div>

      <ConfirmDialog
        open={pendingAction !== null}
        onOpenChange={(open) => !open && setPendingAction(null)}
        title={pendingAction?.type === 'delete' ? 'Delete Node?' : 'Change Kind?'}
        description={
          pendingAction?.type === 'delete'
            ? `This will delete this node and ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
            : `Changing the kind will delete ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
        }
        confirmText={pendingAction?.type === 'delete' ? 'Delete' : 'Change Kind'}
        onConfirm={handleConfirmAction}
        isDestructive
      />

      {isExpanded && node.children && node.children.length > 0 && (
        <div className='mt-2 space-y-2'>
          {node.children.map((child, index) => (
            <OperationRow
              key={child.id}
              node={child}
              depth={depth + 1}
              isFirst={index === 0}
              isLast={index === node.children!.length - 1}
              availableConstants={availableConstants}
              allowedKinds={validChildKinds}
              allNodes={allNodes}
              onUpdate={(updates) => {
                const newChildren = [...node.children!];
                newChildren[index] = { ...child, ...updates };
                onUpdate({ children: newChildren });
              }}
              onRemove={() => {
                const newChildren = node.children!.filter((_, i) => i !== index);
                onUpdate({ children: newChildren });
              }}
              onAddChild={() => {
                const newGrandChild: UINode = {
                  id: Date.now().toString() + Math.random(),
                  kind: '',
                  params: {},
                  children: [],
                };
                const newChildren = [...node.children!];
                newChildren[index] = {
                  ...child,
                  children: [...(child.children || []), newGrandChild],
                };
                onUpdate({ children: newChildren });
              }}
              onAddTemplateChildren={(templateNodes) => {
                const newChildren = [...node.children!];
                newChildren[index] = {
                  ...child,
                  children: [...(child.children || []), ...templateNodes],
                };
                onUpdate({ children: newChildren });
              }}
              onCopy={() => {
                onUpdate({ children: [...node.children!, deepCopyNode(child)] });
              }}
              onMoveUp={() => {
                if (index === 0) return;
                const newChildren = [...node.children!];
                [newChildren[index - 1], newChildren[index]] = [newChildren[index], newChildren[index - 1]];
                onUpdate({ children: newChildren });
              }}
              onMoveDown={() => {
                if (index >= node.children!.length - 1) return;
                const newChildren = [...node.children!];
                [newChildren[index], newChildren[index + 1]] = [newChildren[index + 1], newChildren[index]];
                onUpdate({ children: newChildren });
              }}
            />
          ))}
        </div>
      )}
    </div>
  );
}
