'use client';

import { Button } from './ui/button.tsx';
import type { UINode, ConstantDefinition } from '@molstar/state-builder';
import {
  getValidChildren,
  isTerminalKind,
  countSubtreeNodes,
  deepCopyNode,
  isAutoGeneratedRef,
  generateDefaultRef,
} from '@molstar/state-builder';
import { ConfirmDialog } from './ui/confirm-dialog.tsx';
import { detectCompositeSequence } from '@molstar/state-builder/types/composite-sequences';
import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-react';
import { useState } from 'react';
import { cn } from './lib/utils.ts';
import { TreeLines } from './components/TreeLines.tsx';
import { KindLabel } from './components/KindLabel.tsx';
import { OperationActions } from './components/OperationActions.tsx';
import { CompositeRow } from './CompositeRow.tsx';
import { PrimitivesRow } from './PrimitivesRow.tsx';
import { getNodeSummary } from './node-summary.ts';
import { DownloadHelper } from './DownloadHelper.tsx';
import { ParseHelper } from './ParseHelper.tsx';
import { StructureHelper } from './StructureHelper.tsx';
import { RepresentationHelper } from './RepresentationHelper.tsx';
import { ColorHelper } from './ColorHelper.tsx';
import { TransformHelper } from './TransformHelper.tsx';
import { OpacityHelper } from './OpacityHelper.tsx';
import { LabelHelper } from './LabelHelper.tsx';
import { TooltipHelper } from './TooltipHelper.tsx';
import { CanvasHelper } from './CanvasHelper.tsx';
import { ClipHelper } from './ClipHelper.tsx';
import { VolumeHelper } from './VolumeHelper.tsx';
import { VolumeRepresentationHelper } from './VolumeRepresentationHelper.tsx';
import { SelectorHelper } from './SelectorHelper.tsx';
import { PrimitiveHelper } from './PrimitiveHelper.tsx';
import { FocusHelper } from './FocusHelper.tsx';
import { ColorFromUriHelper } from './ColorFromUriHelper.tsx';
import { ColorFromSourceHelper } from './ColorFromSourceHelper.tsx';
import { LabelFromUriHelper } from './LabelFromUriHelper.tsx';
import { LabelFromSourceHelper } from './LabelFromSourceHelper.tsx';
import { TooltipFromUriHelper } from './TooltipFromUriHelper.tsx';
import { TooltipFromSourceHelper } from './TooltipFromSourceHelper.tsx';
import { ComponentFromUriHelper } from './ComponentFromUriHelper.tsx';
import { ComponentFromSourceHelper } from './ComponentFromSourceHelper.tsx';
import { InterpolateHelper } from './InterpolateHelper.tsx';

interface OperationRowProps {
  node: UINode;
  onUpdate: (updates: Partial<UINode>) => void;
  onRemove: () => void;
  onAddChild?: () => void;
  onAddTemplateChildren?: (nodes: UINode[]) => void;
  onCopy?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  depth?: number;
  isLast?: boolean;
  isFirst?: boolean;
  availableConstants?: ConstantDefinition[];
  allowedKinds?: readonly MVSKind[];
  allNodes?: UINode[];
}

export function OperationRow({
  node,
  onUpdate,
  onRemove,
  onAddChild,
  onAddTemplateChildren,
  onCopy,
  onMoveUp,
  onMoveDown,
  depth = 0,
  isLast = false,
  isFirst = false,
  availableConstants = [],
  allowedKinds,
  allNodes = [],
}: OperationRowProps) {
  const [isExpanded, setIsExpanded] = useState(true);
  const [customOpen, setCustomOpen] = useState(false);
  const [customInput, setCustomInput] = useState(() =>
    node.custom != null ? JSON.stringify(node.custom, null, 2) : ''
  );
  const [customError, setCustomError] = useState('');
  const [helperOpen, setHelperOpen] = useState(false);

  const [pendingAction, setPendingAction] = useState<{
    type: 'delete' | 'kindChange';
    newKind?: MVSKind;
  } | null>(null);

  const childCount = node.children?.length || 0;
  const subtreeCount = countSubtreeNodes(node);
  const compositeMatch = detectCompositeSequence(node);

  if (compositeMatch) {
    return (
      <CompositeRow
        sequence={compositeMatch.sequence}
        rootNode={node}
        exitNode={compositeMatch.exitNode}
        onUpdate={onUpdate}
        onRemove={onRemove}
        onCopy={onCopy}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        depth={depth}
        isFirst={isFirst}
        isLast={isLast}
        availableConstants={availableConstants}
        allowedKinds={allowedKinds}
        allNodes={allNodes}
      />
    );
  }

  if (node.kind === 'primitives') {
    return (
      <PrimitivesRow
        node={node}
        onUpdate={onUpdate}
        onRemove={onRemove}
        onCopy={onCopy}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        depth={depth}
        isFirst={isFirst}
        isLast={isLast}
        availableConstants={availableConstants}
        allowedKinds={allowedKinds}
        allNodes={allNodes}
      />
    );
  }

  const shouldAutoRef = !node.ref || isAutoGeneratedRef(node.ref);

  const handleKindChange = (kind: MVSKind) => {
    const ref = shouldAutoRef ? generateDefaultRef(kind, allNodes) : undefined;
    if (childCount > 0) {
      setPendingAction({ type: 'kindChange', newKind: kind });
    } else {
      onUpdate({ kind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
  };

  const handleCompositeSelect = (compositeNode: UINode) => {
    onUpdate({
      kind: compositeNode.kind,
      params: compositeNode.params,
      children: compositeNode.children,
      ref: compositeNode.ref,
    });
  };

  const handleRemove = () => {
    if (childCount > 0) setPendingAction({ type: 'delete' });
    else onRemove();
  };

  const handleConfirmAction = () => {
    if (!pendingAction) return;
    if (pendingAction.type === 'delete') {
      onRemove();
    } else if (pendingAction.type === 'kindChange' && pendingAction.newKind) {
      const ref = shouldAutoRef ? generateDefaultRef(pendingAction.newKind, allNodes) : undefined;
      onUpdate({ kind: pendingAction.newKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
    setPendingAction(null);
  };

  const handleCustomInputChange = (v: string) => {
    setCustomInput(v);
    if (!v.trim()) { setCustomError(''); onUpdate({ custom: undefined }); return; }
    try {
      const parsed = JSON.parse(v);
      setCustomError('');
      onUpdate({ custom: parsed });
    } catch {
      setCustomError('Invalid JSON');
    }
  };

  const canHaveChildren = !isTerminalKind(node.kind);
  const summary = getNodeSummary(node);
  const isUnconfigured = !node.kind;

  const renderHelper = () => {
    const helperProps = { node, onUpdate, open: helperOpen, onOpenChange: setHelperOpen };
    switch (node.kind as string) {
      case 'download': return <DownloadHelper {...helperProps} />;
      case 'parse': return <ParseHelper {...helperProps} />;
      case 'structure': return <StructureHelper {...helperProps} />;
      case 'representation': return <RepresentationHelper {...helperProps} />;
      case 'color': return <ColorHelper {...helperProps} availableConstants={availableConstants} />;
      case 'transform': return <TransformHelper {...helperProps} />;
      case 'component': return <SelectorHelper {...helperProps} />;
      case 'opacity': return <OpacityHelper {...helperProps} />;
      case 'label': return <LabelHelper {...helperProps} />;
      case 'tooltip': return <TooltipHelper {...helperProps} />;
      case 'canvas': return <CanvasHelper {...helperProps} />;
      case 'clip': return <ClipHelper {...helperProps} />;
      case 'volume': return <VolumeHelper {...helperProps} />;
      case 'volume_representation': return <VolumeRepresentationHelper {...helperProps} />;
      case 'primitives': return <PrimitiveHelper {...helperProps} />;
      case 'focus': return <FocusHelper {...helperProps} />;
      case 'color_from_uri': return <ColorFromUriHelper {...helperProps} />;
      case 'color_from_source': return <ColorFromSourceHelper {...helperProps} />;
      case 'label_from_uri': return <LabelFromUriHelper {...helperProps} />;
      case 'label_from_source': return <LabelFromSourceHelper {...helperProps} />;
      case 'tooltip_from_uri': return <TooltipFromUriHelper {...helperProps} />;
      case 'tooltip_from_source': return <TooltipFromSourceHelper {...helperProps} />;
      case 'component_from_uri': return <ComponentFromUriHelper {...helperProps} />;
      case 'component_from_source': return <ComponentFromSourceHelper {...helperProps} />;
      case 'interpolate': return <InterpolateHelper {...helperProps} />;
      default: return null;
    }
  };

  return (
    <div className='relative' style={{ marginLeft: depth > 0 ? '20px' : '0' }}>
      <TreeLines depth={depth} isLast={isLast} />

      <div className={cn('border rounded-lg px-3 py-2 bg-card shadow-sm flex items-center gap-2', isUnconfigured && 'border-dashed opacity-70')}>
        {/* Expand/collapse */}
        {canHaveChildren ? (
          <Button
            variant='ghost'
            size='sm'
            onClick={() => setIsExpanded(!isExpanded)}
            className='h-6 w-6 p-0 shrink-0'
          >
            {isExpanded ? <ChevronDownIcon className='size-3' /> : <ChevronRightIcon className='size-3' />}
          </Button>
        ) : (
          <span className='inline-block w-6 h-6 shrink-0' />
        )}

        {/* Kind label (select trigger) */}
        <KindLabel
          value={node.kind}
          onChange={handleKindChange}
          onCompositeSelect={handleCompositeSelect}
          allowedKinds={allowedKinds}
        />

        {/* Summary button */}
        <button
          type='button'
          onClick={() => node.kind && setHelperOpen(true)}
          disabled={!node.kind}
          className={cn(
            'flex-1 min-w-0 text-left text-xs px-2 py-1 rounded-md border bg-muted/40 truncate transition-colors',
            node.kind
              ? 'hover:bg-muted hover:border-border cursor-pointer text-foreground'
              : 'text-muted-foreground italic cursor-default border-transparent bg-transparent'
          )}
        >
          {summary ?? (node.kind ? 'click to configure…' : 'select kind first…')}
        </button>

        {/* Actions dropdown */}
        <OperationActions
          canHaveChildren={canHaveChildren}
          isFirst={isFirst}
          isLast={isLast}
          parentKind={node.kind}
          onMoveUp={onMoveUp}
          onMoveDown={onMoveDown}
          onAddChild={onAddChild}
          onAddTemplateChildren={onAddTemplateChildren}
          onCopy={onCopy}
          onRemove={handleRemove}
        />

        {/* Helper modal */}
        {renderHelper()}
      </div>

      {/* Custom data expander */}
      <div className='mt-1 px-3'>
        <button
          type='button'
          className='flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors'
          onClick={() => setCustomOpen((o) => !o)}
        >
          <ChevronRightIcon className={cn('size-3 transition-transform', customOpen && 'rotate-90')} />
          Custom data
          {node.custom != null && <span className='ml-1 size-1.5 rounded-full bg-primary inline-block' />}
        </button>
        {customOpen && (
          <div className='mt-1'>
            <textarea
              className='w-full text-xs font-mono border rounded-md p-2 min-h-[80px] resize-y bg-background'
              placeholder='{ "key": "value" }'
              value={customInput}
              onChange={(e) => handleCustomInputChange(e.target.value)}
              spellCheck={false}
            />
            {customError && <p className='text-xs text-destructive mt-1'>{customError}</p>}
          </div>
        )}
      </div>

      <ConfirmDialog
        open={pendingAction !== null}
        onOpenChange={(open) => !open && setPendingAction(null)}
        title={pendingAction?.type === 'delete' ? 'Delete Node?' : 'Change Kind?'}
        description={
          pendingAction?.type === 'delete'
            ? `This will delete this node and ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
            : `Changing the kind will delete ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
        }
        confirmText={pendingAction?.type === 'delete' ? 'Delete' : 'Change Kind'}
        onConfirm={handleConfirmAction}
        isDestructive
      />

      {isExpanded && node.children && node.children.length > 0 && (
        <div className='mt-2 space-y-2'>
          {node.children.map((child, index) => (
            <OperationRow
              key={child.id}
              node={child}
              onUpdate={(updates) => {
                const newChildren = [...(node.children ?? [])];
                newChildren[index] = { ...child, ...updates };
                onUpdate({ children: newChildren });
              }}
              onRemove={() => {
                const newChildren = (node.children ?? []).filter((_, i) => i !== index);
                onUpdate({ children: newChildren });
              }}
              onAddChild={() => {
                const newChildren = [...(node.children ?? []), { id: crypto.randomUUID(), kind: '' as MVSKind, params: {}, children: [] }];
                onUpdate({ children: newChildren });
              }}
              onAddTemplateChildren={(nodes) => {
                const newChildren = [...(node.children ?? []), ...nodes];
                onUpdate({ children: newChildren });
              }}
              onCopy={() => {
                const copy = deepCopyNode(child);
                const newChildren = [...(node.children ?? [])];
                newChildren.splice(index + 1, 0, copy);
                onUpdate({ children: newChildren });
              }}
              onMoveUp={index > 0 ? () => {
                const newChildren = [...(node.children ?? [])];
                [newChildren[index - 1], newChildren[index]] = [newChildren[index], newChildren[index - 1]];
                onUpdate({ children: newChildren });
              } : undefined}
              onMoveDown={index < (node.children?.length ?? 0) - 1 ? () => {
                const newChildren = [...(node.children ?? [])];
                [newChildren[index], newChildren[index + 1]] = [newChildren[index + 1], newChildren[index]];
                onUpdate({ children: newChildren });
              } : undefined}
              depth={(depth ?? 0) + 1}
              isFirst={index === 0}
              isLast={index === (node.children?.length ?? 0) - 1}
              availableConstants={availableConstants}
              allowedKinds={node.kind ? getValidChildren(node.kind as MVSKind) : undefined}
              allNodes={allNodes}
            />
          ))}
        </div>
      )}
    </div>
  );
}
