'use client';

import { Button } from './ui/button.tsx';
import { Input } from './ui/input.tsx';
import { Label } from './ui/label.tsx';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select.tsx';
import type { UINode, ConstantDefinition } from '@molstar/state-builder';
import {
  countSubtreeNodes,
  isAutoGeneratedRef,
  generateDefaultRef,
  MVS_KIND_LABELS,
} from '@molstar/state-builder';
import { ConfirmDialog } from './ui/confirm-dialog.tsx';
import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-react';
import { useState } from 'react';
import { TreeLines } from './components/TreeLines.tsx';
import { OperationActions } from './components/OperationActions.tsx';
import { PrimitivesFields } from './components/fields/PrimitivesFields.tsx';
import { PrimitiveHelper } from './PrimitiveHelper.tsx';

interface PrimitivesRowProps {
  node: UINode;
  onUpdate: (updates: Partial<UINode>) => void;
  onRemove: () => void;
  onCopy?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  depth?: number;
  isFirst?: boolean;
  isLast?: boolean;
  availableConstants?: ConstantDefinition[];
  allowedKinds?: readonly MVSKind[];
  allNodes?: UINode[];
}

export function PrimitivesRow({
  node,
  onUpdate,
  onRemove,
  onCopy,
  onMoveUp,
  onMoveDown,
  depth = 0,
  isFirst = false,
  isLast = false,
  allNodes = [],
}: PrimitivesRowProps) {
  const [isExpanded, setIsExpanded] = useState(true);
  const [pendingAction, setPendingAction] = useState<{
    type: 'delete' | 'kindChange';
    newKind?: MVSKind;
  } | null>(null);

  const primitiveChildren = (node.children ?? []).filter((c) => c.kind === 'primitive');
  const subtreeCount = countSubtreeNodes(node);
  const shouldAutoRef = !node.ref || isAutoGeneratedRef(node.ref);

  const handleKindChange = (kind: string) => {
    if (kind === 'primitives') return;
    if (subtreeCount > 0) {
      setPendingAction({ type: 'kindChange', newKind: kind as MVSKind });
    } else {
      const ref = shouldAutoRef ? generateDefaultRef(kind as MVSKind, allNodes) : undefined;
      onUpdate({ kind: kind as MVSKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
  };

  const handleRemove = () => {
    if (subtreeCount > 0) {
      setPendingAction({ type: 'delete' });
    } else {
      onRemove();
    }
  };

  const handleConfirmAction = () => {
    if (!pendingAction) return;
    if (pendingAction.type === 'delete') {
      onRemove();
    } else if (pendingAction.type === 'kindChange' && pendingAction.newKind) {
      const ref = shouldAutoRef ? generateDefaultRef(pendingAction.newKind, allNodes) : undefined;
      onUpdate({ kind: pendingAction.newKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
    setPendingAction(null);
  };

  const handlePrimitivesApply = (newPrimitives: UINode[]) => {
    onUpdate({ children: newPrimitives });
  };

  return (
    <div className='relative' style={{ marginLeft: depth > 0 ? '20px' : '0' }}>
      <TreeLines depth={depth} isLast={isLast} />

      <div className='border rounded-md p-2 bg-card'>
        <div className='flex gap-2 items-end flex-wrap'>
          {/* Expand/collapse */}
          <Button
            variant='ghost'
            size='sm'
            onClick={() => setIsExpanded(!isExpanded)}
            className='h-8 w-8 p-0'
            title={isExpanded ? 'Collapse' : 'Expand'}
          >
            {isExpanded ? (
              <ChevronDownIcon className='size-4' />
            ) : (
              <ChevronRightIcon className='size-4' />
            )}
          </Button>

          {/* Kind selector — shows 'primitives', allows switching away */}
          <div className='w-40'>
            <Label className='text-xs'>Kind</Label>
            <Select value='primitives' onValueChange={handleKindChange}>
              <SelectTrigger size='sm'>
                <SelectValue>{MVS_KIND_LABELS['primitives'] ?? 'Primitives'}</SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value='primitives'>
                  {MVS_KIND_LABELS['primitives'] ?? 'Primitives'}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Container params: color, opacity, label_attachment, label_color */}
          <PrimitivesFields
            params={node.params}
            onChange={(params) => onUpdate({ params })}
          />

          {/* PrimitiveHelper trigger */}
          <PrimitiveHelper primitives={primitiveChildren} onApply={handlePrimitivesApply} />

          {/* Ref */}
          <div className='w-24'>
            <Label className='text-xs'>Ref</Label>
            <Input
              className='h-8 text-sm'
              placeholder='name'
              value={node.ref ?? ''}
              onChange={(e) => onUpdate({ ref: e.target.value || undefined })}
              title='Reference name'
            />
          </div>

          {/* Action buttons */}
          <OperationActions
            canHaveChildren={false}
            isFirst={isFirst}
            isLast={isLast}
            parentKind='primitives'
            onMoveUp={onMoveUp}
            onMoveDown={onMoveDown}
            onCopy={onCopy}
            onRemove={handleRemove}
          />
        </div>
      </div>

      <ConfirmDialog
        open={pendingAction !== null}
        onOpenChange={(open) => !open && setPendingAction(null)}
        title={pendingAction?.type === 'delete' ? 'Delete Node?' : 'Change Kind?'}
        description={
          pendingAction?.type === 'delete'
            ? `This will delete this node and ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
            : `Changing the kind will delete ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
        }
        confirmText={pendingAction?.type === 'delete' ? 'Delete' : 'Change Kind'}
        onConfirm={handleConfirmAction}
        isDestructive
      />

      {/* Summary of primitives when expanded */}
      {isExpanded && primitiveChildren.length > 0 && (
        <div className='mt-1 pl-4'>
          <p className='text-xs text-muted-foreground'>
            {primitiveChildren.length} primitive{primitiveChildren.length > 1 ? 's' : ''} (managed in helper)
          </p>
        </div>
      )}
    </div>
  );
}
