'use client';

import { Button } from './base/button.tsx';
import type { UINode, ConstantDefinition } from '@molstar/state-builder';
import {
  countSubtreeNodes,
  isAutoGeneratedRef,
  generateDefaultRef,
  MVS_KIND_LABELS,
} from '@molstar/state-builder';
import { ConfirmDialog } from './base/confirm-dialog.tsx';
import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-react';
import { useState } from 'react';
import { TreeLines } from './components/TreeLines.tsx';
import { OperationActions } from './components/OperationActions.tsx';
import { PrimitiveHelper } from './helpers/PrimitiveHelper.tsx';
import { getColorForKind } from './node-categories.ts';
import { getNodeSummary } from './node-summary.ts';

interface PrimitivesRowProps {
  node: UINode;
  onUpdate: (updates: Partial<UINode>) => void;
  onRemove: () => void;
  onCopy?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  depth?: number;
  isFirst?: boolean;
  isLast?: boolean;
  availableConstants?: ConstantDefinition[];
  allowedKinds?: readonly MVSKind[];
  allNodes?: UINode[];
}

export function PrimitivesRow({
  node,
  onUpdate,
  onRemove,
  onCopy,
  onMoveUp,
  onMoveDown,
  depth = 0,
  isFirst = false,
  isLast = false,
  allNodes = [],
}: PrimitivesRowProps) {
  const [isExpanded, setIsExpanded] = useState(true);
  const [helperOpen, setHelperOpen] = useState(false);
  const [pendingAction, setPendingAction] = useState<{
    type: 'delete' | 'kindChange';
    newKind?: MVSKind;
  } | null>(null);

  const primitiveChildren = (node.children ?? []).filter((c) => c.kind === 'primitive');
  const subtreeCount = countSubtreeNodes(node);
  const shouldAutoRef = !node.ref || isAutoGeneratedRef(node.ref);

  const handleKindChange = (kind: string) => {
    if (kind === 'primitives') return;
    if (subtreeCount > 0) {
      setPendingAction({ type: 'kindChange', newKind: kind as MVSKind });
    } else {
      const ref = shouldAutoRef ? generateDefaultRef(kind as MVSKind, allNodes) : undefined;
      onUpdate({ kind: kind as MVSKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
  };

  const handleRemove = () => {
    if (subtreeCount > 0) {
      setPendingAction({ type: 'delete' });
    } else {
      onRemove();
    }
  };

  const handleConfirmAction = () => {
    if (!pendingAction) return;
    if (pendingAction.type === 'delete') {
      onRemove();
    } else if (pendingAction.type === 'kindChange' && pendingAction.newKind) {
      const ref = shouldAutoRef ? generateDefaultRef(pendingAction.newKind, allNodes) : undefined;
      onUpdate({ kind: pendingAction.newKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
    setPendingAction(null);
  };

  void handleKindChange; // kept for future kind-switching support

  const dotColor = getColorForKind('primitives');
  const kindLabel = MVS_KIND_LABELS['primitives'] ?? 'Primitives';
  const summary = getNodeSummary(node);

  return (
    <div className='relative' style={{ marginLeft: depth > 0 ? '20px' : '0' }}>
      <TreeLines depth={depth} isLast={isLast} />

      <div className='border rounded-lg px-3 py-2 bg-card shadow-sm flex items-center gap-2'>
        {/* Expand/collapse */}
        <Button
          variant='ghost'
          size='sm'
          onClick={() => setIsExpanded(!isExpanded)}
          className='h-6 w-6 p-0 shrink-0'
          title={isExpanded ? 'Collapse' : 'Expand'}
        >
          {isExpanded ? (
            <ChevronDownIcon className='size-3' />
          ) : (
            <ChevronRightIcon className='size-3' />
          )}
        </Button>

        {/* Kind label */}
        <span className='text-xs font-semibold text-muted-foreground flex items-center gap-1.5 min-w-[90px]'>
          <span
            className='inline-block rounded-full shrink-0'
            style={{ width: 7, height: 7, background: dotColor }}
          />
          {kindLabel}
        </span>

        {/* Summary button — opens PrimitiveHelper */}
        <button
          type='button'
          onClick={() => setHelperOpen(true)}
          className='flex-1 min-w-0 text-left text-xs px-2 py-1 rounded-md border bg-muted/40 truncate hover:bg-muted hover:border-border cursor-pointer text-foreground transition-colors'
        >
          {summary ?? (primitiveChildren.length === 0 ? 'click to add primitives…' : `${primitiveChildren.length} primitive${primitiveChildren.length !== 1 ? 's' : ''}`)}
        </button>

        <OperationActions
          canHaveChildren={false}
          isFirst={isFirst}
          isLast={isLast}
          parentKind='primitives'
          onMoveUp={onMoveUp}
          onMoveDown={onMoveDown}
          onCopy={onCopy}
          onRemove={handleRemove}
        />

        <PrimitiveHelper
          node={node}
          onUpdate={onUpdate}
          open={helperOpen}
          onOpenChange={setHelperOpen}
        />
      </div>

      <ConfirmDialog
        open={pendingAction !== null}
        onOpenChange={(open) => !open && setPendingAction(null)}
        title={pendingAction?.type === 'delete' ? 'Delete Node?' : 'Change Kind?'}
        description={
          pendingAction?.type === 'delete'
            ? `This will delete this node and ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
            : `Changing the kind will delete ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
        }
        confirmText={pendingAction?.type === 'delete' ? 'Delete' : 'Change Kind'}
        onConfirm={handleConfirmAction}
        isDestructive
      />

      {/* Children summary when expanded */}
      {isExpanded && primitiveChildren.length > 0 && (
        <div className='mt-1 pl-4'>
          <p className='text-xs text-muted-foreground'>
            {primitiveChildren.length} primitive{primitiveChildren.length > 1 ? 's' : ''} (managed in helper)
          </p>
        </div>
      )}
    </div>
  );
}
