// Export UI builder types (MVS format)
export type {
  UINode,
  UIBuilderState,
  ConstantType,
  ConstantEntry,
  ConstantDefinition,
  ConstantRef,
  RawMVSNode,
  RawMVSTree,
} from './core/index.ts';
export {
  createEmptyNode,
  createEmptyConstant,
  createConstantRef,
  isConstantRef,
  countSubtreeNodes,
  deepCopyNode,
  mvsNodeToUINode,
  mvsTreeToUINodes,
  uiNodeToMVSNode,
  uiNodesToMVSTree,
  isAutoGeneratedRef,
  generateDefaultRef,
  assignMissingRefs,
} from './core/index.ts';

// Export composite sequences
export type { CompositeSequence } from './core/index.ts';
export {
  COMPOSITE_SEQUENCES,
  DOWNLOAD_PARSE_SEQUENCE,
  detectCompositeSequence,
  createDownloadParseNodes,
  getCompositeValidChildren,
} from './core/index.ts';

// Export MVS tree grammar (valid parent-child relationships)
export {
  MVS_KIND_LABELS,
  MVS_ALL_KINDS,
  MVS_SELECTABLE_KINDS,
  MVS_VALID_CHILDREN,
  getValidChildren,
  canHaveChild,
  getTerminalKinds,
  isTerminalKind,
} from './core/index.ts';

// Export MVS parameter types and validators
export type {
  StructureType,
  ParseFormat,
  RepresentationType,
  ComponentSelector,
  PrimitiveKind,
  ClipType,
  VolumeRepresentationType,
  MolstarColorTheme,
  CarbonColorOption,
  LabelAttachment,
} from './params/index.ts';
export {
  STRUCTURE_TYPES,
  PARSE_FORMATS,
  REPRESENTATION_TYPES,
  COMPONENT_SELECTORS,
  PRIMITIVE_KINDS,
  CLIP_TYPES,
  VOLUME_REPRESENTATION_TYPES,
  MOLSTAR_COLOR_THEMES,
  CARBON_COLOR_OPTIONS,
  LABEL_ATTACHMENT_OPTIONS,
  getActiveValues,
  isValidStructureType,
  isValidParseFormat,
  isValidRepresentationType,
  isValidPrimitiveKind,
  validateStructureParams,
  validateParseParams,
  validateRepresentationParams,
} from './params/index.ts';

// Export selector builder types and utilities
export type {
  LabeledValue,
  ComponentSelectorObject,
  ComponentSelectorValue,
  SelectorBuilderMode,
  StructureMetadata,
  ChainInfo,
  LigandInfo,
  ParsedSelector,
} from './selector/index.ts';
export {
  DEFAULT_CHAIN_IDS,
  COMMON_LIGAND_IDS,
  QUICK_SELECTOR_PRESETS,
  buildChainSelector,
  buildResidueSelector,
  buildLigandSelector,
  buildUnionSelector,
  parseSelector,
  selectorToString,
  parseRawSelectorInput,
  formatSelectorPreview,
  getAvailableChains,
  getAvailableLigands,
  getResidueRange,
} from './selector/index.ts';

// Export structure metadata extraction utilities
export type { RawChainData, RawLigandData } from './selector/index.ts';
export {
  buildStructureMetadata,
  mergeStructureMetadata,
} from './selector/index.ts';

// Export selector filter utility
export { filterMetadataBySelector } from './selector/index.ts';

// Export tree templates
export type {
  MVSNodeSnippet,
  TreeTemplate,
  TemplateCategory,
} from './template/index.ts';
export {
  BUILTIN_TEMPLATES,
  getTemplatesForParentKind,
  instantiateTemplate,
} from './template/index.ts';

// Export template adapter
export type { TemplateAdapter } from './template/index.ts';
export { BUILTIN_ADAPTER_ID } from './template/index.ts';

// Export template registry
export type { TemplateRegistry } from './template/index.ts';
export { createTemplateRegistry } from './template/index.ts';

// Export transform parameter types and utilities
export type {
  Vec3,
  TransformParams,
  RotationPresetDef,
} from './transform/index.ts';
export {
  IDENTITY_3x3,
  IDENTITY_4x4,
  ROTATION_PRESETS,
  columnToRowMajor3,
  rowToColumnMajor3,
  columnToRowMajor4,
  rowToColumnMajor4,
  eulerToMatrix,
  matrixToEuler,
  rotationPreset,
  isValidRotationMatrix,
  mulMat3Vec3,
  projectIsometric,
  composeTransformMatrix,
  decomposeTransformMatrix,
} from './transform/index.ts';

// Export camera data type and camera parameter types/utilities
export type { CameraData, CameraParams, CameraPresetDef } from './camera/index.ts';
export {
  DEFAULT_UP,
  CAMERA_PRESETS,
  isDefaultUp,
  snapshotToCameraParams,
  extractCameraFromUINodes,
} from './camera/index.ts';

// Export animation builder types and utilities
export type {
  InterpolationKind,
  EasingType,
  SimpleInterpolationStep,
  TransformMatrixInterpolationStep,
  InterpolationStep,
  TrackballSpin,
  AnimationParams,
  AnimationPreset,
  RefInfo,
} from './animation/index.ts';
export {
  INTERPOLATION_KINDS,
  EASING_OPTIONS,
  ANIMATION_PRESETS,
  KIND_COLORS,
  VALID_REF_KINDS,
  PROPERTY_KIND_MAP,
  createDefaultAnimationParams,
  createEmptyInterpolationStep,
  applyPreset,
  convertAnimationToMVSNode,
  convertMVSNodeToAnimationParams,
  extractAnimationFromUINodes,
  extractRefsFromNodes,
  filterRefsForKind,
  getAnimatableProperties,
  computeAnimationDuration,
} from './animation/index.ts';

// Export code evaluator (code → builder state)
export type { EvaluateCodeOptions } from './code-evaluator.ts';
export { evaluateCodeToMVSTree } from './code-evaluator.ts';

export const placeholder = 'state-builder';

