import { useEffect, useRef } from 'react';
import {
  uiNodeToMVSNode,
  isDefaultUp,
  convertAnimationToMVSNode,
} from '../../../state-builder/index.ts';
import type { UINode, ConstantDefinition, CameraParams, AnimationParams } from '../../../state-builder/index.ts';
import { ASTFactory } from '../../../state-builder/compiler/ast/factory.ts';
import { CodeGenerator } from '../../../state-builder/compiler/codegen/generator.ts';
import { useAutoGenerateOnMount } from '../../state/auto-generate-context.ts';
import type { NotifyFn } from '../../state/notifications.ts';

interface UseCodeGenerationParams {
  nodes: UINode[];
  constants: ConstantDefinition[];
  camera: CameraParams | null;
  animation: AnimationParams | null;
  storyConstants: ConstantDefinition[];
  onCodeGenerated: ((code: string) => void) | null;
  notify: NotifyFn;
}

export function useCodeGeneration({ nodes, constants, camera, animation, storyConstants, onCodeGenerated, notify }: UseCodeGenerationParams) {
  const generateCodeFromNodes = (
    nodesToGenerate: UINode[],
    constantsToInclude: ConstantDefinition[] = [...storyConstants, ...constants],
    cameraToInclude: CameraParams | null = camera,
    animationToInclude: AnimationParams | null = animation,
  ) => {
    try {
      if (nodesToGenerate.length === 0) {
        notify({ type: 'error', message: 'No nodes to generate code from. Add nodes or import an MVSTree first.' });
        return;
      }

      // Build children list, appending camera node if set
      const children = nodesToGenerate.map(uiNodeToMVSNode);
      if (cameraToInclude) {
        const cameraParams: Record<string, unknown> = {
          position: cameraToInclude.position,
          target: cameraToInclude.target,
        };
        if (cameraToInclude.up && !isDefaultUp(cameraToInclude.up)) {
          cameraParams.up = cameraToInclude.up;
        }
        children.push({ kind: 'camera', params: cameraParams, ref: cameraToInclude.ref ?? 'camera' });
      }

      // Append animation node if set
      if (animationToInclude && (animationToInclude.steps.length > 0 || animationToInclude.trackball?.enabled)) {
        children.push(convertAnimationToMVSNode(animationToInclude));
      }

      // Build MVS data structure with root wrapper
      const mvsData = {
        root: {
          kind: 'root' as const,
          params: {},
          children,
        },
        metadata: {
          timestamp: new Date().toISOString(),
        },
      };

      console.log('MVS Data:', JSON.stringify(mvsData, null, 2));

      // Pass directly to compiler
      const ast = ASTFactory.fromMVSData(mvsData);

      // Filter out incomplete constants (no name or no entries)
      const validConstants = constantsToInclude.filter(
        (c) => c.name && c.entries.length > 0 && c.entries.some((e) => e.key)
      );

      const generator = new CodeGenerator({
        includeSectionMarkers: true,
        builderVar: 'builder',
        includeComments: true,
        constants: validConstants,
      });

      const code = generator.generate(ast);

      console.log('Generated code:', code);

      // Call the callback if provided
      if (onCodeGenerated) {
        onCodeGenerated(code);
        notify({ type: 'success', message: 'Code generated and applied to editor!' });
      } else {
        notify({ type: 'success', message: 'Code generated successfully! (no callback provided)' });
      }
    } catch (error) {
      console.error('Code generation error:', error);
      notify({ type: 'error', message: `Failed to generate code: ${error instanceof Error ? error.message : String(error)}` });
    }
  };

  const generateCode = () => {
    generateCodeFromNodes(nodes);
  };

  // After-apply auto-codegen: set via markPendingCodeGen from NodeHelperBase Apply
  // (through AfterApplyContext); this effect fires once React has committed the
  // new nodes so generateCodeFromNodes sees fresh state.
  const pendingCodeGenRef = useRef(false);
  useEffect(() => {
    if (pendingCodeGenRef.current && nodes.length > 0) {
      pendingCodeGenRef.current = false;
      generateCodeFromNodes(nodes);
    }
    // generateCodeFromNodes is redefined each render (closes over constants/camera/animation),
    // so intentionally omitted — we only want this to fire when nodes changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [nodes]);
  const markPendingCodeGen = () => { pendingCodeGenRef.current = true; };

  // Auto-generate code on mount when initialState was provided
  const autoGenerateOnMount = useAutoGenerateOnMount();
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (!autoGenerateOnMount || hasAutoGenerated.current || nodes.length === 0) return;
    hasAutoGenerated.current = true;
    generateCode();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [nodes]);

  return { generateCode, generateCodeFromNodes, markPendingCodeGen };
}
