#!/usr/bin/env -S deno run --allow-read --allow-write

/// <reference lib="deno.ns" />

/**
 * Generates src/aliases.ts from deno.json imports.
 *
 * Inverts each `"bare-key": "npm:pkg@ver/path"` entry into
 * `"npm:pkg@ver/path": "bare-key"` so Next.js can alias JSR-published
 * `npm:` specifiers back to bare module names for webpack/Turbopack.
 */

const denoJson = JSON.parse(await Deno.readTextFile("./deno.json"));
const imports: Record<string, string> = denoJson.imports ?? {};

const aliases: Record<string, string> = {};

for (const [key, value] of Object.entries(imports)) {
  if (!value.startsWith("npm:")) continue;
  aliases[value] = key;
}

const entries = Object.entries(aliases)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");

const out = `// auto-generated by scripts/generate-aliases.ts — do not edit\nconst aliases: Record<string, string> = {\n${entries}\n};\n\nexport default aliases;\n`;
await Deno.writeTextFile("./src/aliases.ts", out);
console.log(`Generated src/aliases.ts with ${Object.keys(aliases).length} entries`);
