// Auto-generated ref helpers
import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import type { UINode } from './node-types.ts';
import { MVS_ALL_KINDS } from './grammar.ts';

const AUTO_REF_PATTERN = /^(.+?)(\d+)$/;

/**
 * Check whether a ref string looks like an auto-generated ref (e.g. "representation1").
 * Returns true if the ref matches `<validKind><number>`.
 */
export function isAutoGeneratedRef(ref: string): boolean {
  const m = AUTO_REF_PATTERN.exec(ref);
  if (!m) return false;
  return (MVS_ALL_KINDS as readonly string[]).includes(m[1]);
}

/**
 * Collect all refs from a node tree (flat list).
 */
function collectAllRefs(nodes: UINode[]): Set<string> {
  const refs = new Set<string>();
  function traverse(node: UINode) {
    if (node.ref) refs.add(node.ref);
    node.children?.forEach(traverse);
  }
  nodes.forEach(traverse);
  return refs;
}

/**
 * Generate a default ref for a given kind, e.g. "representation1".
 * Picks the lowest available number that doesn't collide with existing refs.
 */
export function generateDefaultRef(kind: MVSKind, allNodes: UINode[]): string {
  const existing = collectAllRefs(allNodes);
  let n = 1;
  while (existing.has(`${kind}${n}`)) n++;
  return `${kind}${n}`;
}

/**
 * Assign auto-generated refs to all nodes in `newNodes` that lack a ref.
 * Avoids collisions with refs in `existingNodes` and refs assigned within the same call.
 * Returns new node objects (does not mutate originals).
 */
export function assignMissingRefs(newNodes: UINode[], existingNodes: UINode[]): UINode[] {
  const usedRefs = collectAllRefs(existingNodes);

  function processNode(node: UINode): UINode {
    const children = node.children?.map(processNode);
    if (node.kind && !node.ref) {
      let n = 1;
      while (usedRefs.has(`${node.kind}${n}`)) n++;
      const ref = `${node.kind}${n}`;
      usedRefs.add(ref);
      return { ...node, ref, ...(children && { children }) };
    }
    if (children) {
      return { ...node, children };
    }
    return node;
  }

  return newNodes.map(processNode);
}
