// deno-lint-ignore-file no-new-func
import { MVSData } from 'molstar/lib/extensions/mvs/mvs-data.js';
import type { ConstantDefinition, RawMVSTree } from './ui-builder.ts';

// AsyncFunction constructor — lets user code use await without wrapping it
// themselves. Matches the execution strategy in src/utils/executeCode.ts.
const AsyncFunction = Object.getPrototypeOf(async function () {
}).constructor as new (...args: string[]) => (...args: unknown[]) => Promise<unknown>;

export interface EvaluateCodeOptions {
  /**
   * ConstantDefinition objects to inject as named scope variables
   * (e.g. `Colors`, `Urls`). Keys are `ConstantDefinition.name`.
   */
  constants?: ConstantDefinition[];
  /**
   * JavaScript code prepended before the scene code — typically story-level
   * helper function definitions (e.g. `function structure(builder, id) {...}`).
   */
  storyCode?: string;
  /**
   * Additional scope variables injected alongside `builder`.
   * Use this to provide math utilities (Vec3, Mat3, etc.) that appear in code
   * generated by earlier builder sessions.
   * Constants override extraScope when keys collide.
   */
  extraScope?: Record<string, unknown>;
}

/**
 * Execute builder-API JavaScript code with the real MVS builder and return
 * the resulting MVS node tree as a `RawMVSTree`.
 *
 * Unlike a Proxy-based mock, this handles any valid builder pattern:
 * helper functions, constants, math utilities, chained calls.
 *
 * Returns `null` when the code cannot be evaluated (syntax error, runtime
 * error, etc.). The caller should surface an appropriate error message.
 */
export async function evaluateCodeToMVSTree(
  code: string,
  options?: EvaluateCodeOptions,
): Promise<RawMVSTree | null> {
  const { constants, storyCode, extraScope } = options ?? {};

  const fullCode = storyCode ? `${storyCode}\n\n${code}` : code;

  // Build scope: extraScope first so constants can override collisions
  const allScope: Record<string, unknown> = { ...extraScope };
  for (const c of constants ?? []) {
    allScope[c.name] = Object.fromEntries(c.entries.map((e) => [e.key, e.value]));
  }

  const scopeArgNames = Object.keys(allScope);
  const scopeArgValues = Object.values(allScope);

  const fn = new AsyncFunction('builder', ...scopeArgNames, fullCode);
  const builder = MVSData.createBuilder();

  try {
    await fn(builder, ...scopeArgValues);
  } catch {
    return null;
  }

  const snapshot = builder.getSnapshot({ title: 'code-to-state', linger_duration_ms: 0, transition_duration_ms: 0 });
  // snapshot.root has the same shape as RawMVSTree (kind, params, children).
  // Animation is stored separately in snapshot.animation (not as a root child), so
  // inject it back as a child so extractAnimationFromUINodes can find it downstream.
  const root = snapshot.root as unknown as RawMVSTree;
  if (snapshot.animation) {
    root.children = [...(root.children ?? []), snapshot.animation as unknown as RawMVSTree];
  }
  return root;
}
