/**
 * Headless UI Builder Types - MVS Format
 *
 * These types define MVS nodes in a mutable format suitable for UI editing.
 * They are compatible with the MVS JSON format used by the compiler.
 *
 * This is a headless layer (no UI dependencies) that allows:
 * - Direct storage of MVS-compatible data structures
 * - Type-safe parameter handling
 * - Direct compilation to JavaScript without conversion layers
 */

import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import { MVS_ALL_KINDS } from './mvs-tree-grammar.ts';

// ============================================
// Constants Types
// ============================================

/**
 * Types of constants supported by the builder
 */
export type ConstantType = 'colors' | 'urls' | 'generic';

/**
 * A single key-value entry in a constant definition
 */
export interface ConstantEntry {
  key: string;
  value: string;
}

/**
 * A constant definition that can be referenced in field components
 */
export interface ConstantDefinition {
  /** Unique ID for React keys */
  id: string;
  /** Variable name for the constant (e.g., "Colors", "Urls") */
  name: string;
  /** Type of constant - affects UI rendering and validation */
  type: ConstantType;
  /** Key-value entries */
  entries: ConstantEntry[];
}

/**
 * Reference to a constant value for use in field components.
 * When a field uses a constant reference instead of a literal value,
 * the code generator will output an unquoted identifier (e.g., Colors.primary)
 */
export interface ConstantRef {
  /** Marker for type detection */
  __constantRef: true;
  /** The constant name (e.g., "Colors") */
  constantName: string;
  /** The key within the constant (e.g., "primary") */
  entryKey: string;
}

/**
 * Type guard for ConstantRef
 */
export function isConstantRef(value: unknown): value is ConstantRef {
  return (
    typeof value === 'object' &&
    value !== null &&
    '__constantRef' in value &&
    (value as ConstantRef).__constantRef === true
  );
}

/**
 * Helper for creating a constant reference
 */
export function createConstantRef(constantName: string, entryKey: string): ConstantRef {
  return {
    __constantRef: true,
    constantName,
    entryKey,
  };
}

/**
 * Helper for creating an empty constant definition
 */
export function createEmptyConstant(type: ConstantType = 'generic'): ConstantDefinition {
  return {
    id: generateId(),
    name: '',
    type,
    entries: [],
  };
}

// ============================================
// UINode Types
// ============================================

/**
 * Mutable MVS node for UI editing
 * This matches the MVS JSON structure but allows mutation for React state
 */
export interface UINode {
  /** Unique ID for React keys (not part of MVS spec) */
  id: string;

  /** MVS node kind */
  kind: MVSKind | '';

  /** Type-safe parameters for this kind */
  params: Record<string, unknown>;

  /** Optional reference name */
  ref?: string;

  /** Custom properties (Molstar-specific extensions like color themes) */
  custom?: Record<string, unknown>;

  /** Child nodes */
  children?: UINode[];
}

/**
 * Complete UI Builder state
 */
export interface UIBuilderState {
  /** Root-level nodes */
  nodes: UINode[];

  /** Constant definitions */
  constants?: ConstantDefinition[];

  /** Metadata */
  metadata?: {
    timestamp?: string;
  };
}

/**
 * Helper for creating empty nodes
 */
export function createEmptyNode(kind: MVSKind | '' = ''): UINode {
  return {
    id: generateId(),
    kind,
    params: {},
    children: [],
  };
}

function generateId(): string {
  return Date.now().toString() + Math.random().toString(36).substr(2, 9);
}

/**
 * Deep-copy a UINode subtree: fresh IDs throughout, refs suffixed with `_copy`.
 */
export function deepCopyNode(node: UINode): UINode {
  return {
    ...node,
    id: `${Date.now()}-${Math.random().toString(36).slice(2)}`,
    ref: node.ref ? `${node.ref}_copy` : undefined,
    children: node.children?.map(deepCopyNode),
  };
}

/**
 * Count total nodes in a subtree (excluding the root node itself)
 */
export function countSubtreeNodes(node: UINode): number {
  if (!node.children || node.children.length === 0) return 0;
  return node.children.reduce(
    (sum, child) => sum + 1 + countSubtreeNodes(child),
    0
  );
}

// ============================================
// Auto-generated Ref Helpers
// ============================================

const AUTO_REF_PATTERN = /^(.+?)(\d+)$/;

/**
 * Check whether a ref string looks like an auto-generated ref (e.g. "representation1").
 * Returns true if the ref matches `<validKind><number>`.
 */
export function isAutoGeneratedRef(ref: string): boolean {
  const m = AUTO_REF_PATTERN.exec(ref);
  if (!m) return false;
  return (MVS_ALL_KINDS as readonly string[]).includes(m[1]);
}

/**
 * Collect all refs from a node tree (flat list).
 */
function collectAllRefs(nodes: UINode[]): Set<string> {
  const refs = new Set<string>();
  function traverse(node: UINode) {
    if (node.ref) refs.add(node.ref);
    node.children?.forEach(traverse);
  }
  nodes.forEach(traverse);
  return refs;
}

/**
 * Generate a default ref for a given kind, e.g. "representation1".
 * Picks the lowest available number that doesn't collide with existing refs.
 */
export function generateDefaultRef(kind: MVSKind, allNodes: UINode[]): string {
  const existing = collectAllRefs(allNodes);
  let n = 1;
  while (existing.has(`${kind}${n}`)) n++;
  return `${kind}${n}`;
}

/**
 * Assign auto-generated refs to all nodes in `newNodes` that lack a ref.
 * Avoids collisions with refs in `existingNodes` and refs assigned within the same call.
 * Returns new node objects (does not mutate originals).
 */
export function assignMissingRefs(newNodes: UINode[], existingNodes: UINode[]): UINode[] {
  const usedRefs = collectAllRefs(existingNodes);

  function processNode(node: UINode): UINode {
    const children = node.children?.map(processNode);
    if (node.kind && !node.ref) {
      let n = 1;
      while (usedRefs.has(`${node.kind}${n}`)) n++;
      const ref = `${node.kind}${n}`;
      usedRefs.add(ref);
      return { ...node, ref, ...(children && { children }) };
    }
    if (children) {
      return { ...node, children };
    }
    return node;
  }

  return newNodes.map(processNode);
}

// ============================================
// MVS JSON Conversion
// ============================================

/**
 * Raw MVS JSON node structure (more permissive than strict MVSNode union)
 */
export interface RawMVSNode {
  kind: string;
  params?: Record<string, unknown>;
  ref?: string;
  custom?: Record<string, unknown>;
  children?: RawMVSNode[];
}

/**
 * MVS Tree root structure
 */
export interface RawMVSTree {
  kind: 'root';
  params?: Record<string, unknown>;
  children?: RawMVSNode[];
}

/**
 * Convert a raw MVS JSON node to UINode by adding IDs recursively.
 *
 * @param node - Raw MVS node from JSON
 * @param idPrefix - Optional prefix for generating unique IDs
 * @returns UINode with generated ID
 */
export function mvsNodeToUINode(node: RawMVSNode, idPrefix = ''): UINode {
  const id = `${idPrefix}${generateId()}`;
  return {
    id,
    kind: node.kind as MVSKind | '',
    params: node.params ?? {},
    ref: node.ref,
    custom: node.custom,
    children: node.children?.map((child, i) => mvsNodeToUINode(child, `${id}_${i}_`)),
  };
}

/**
 * Convert an MVS Tree (root node) to UINode array.
 * Extracts the children of the root and converts them to UINodes.
 *
 * @param tree - MVS Tree with kind 'root'
 * @returns Array of UINodes (root's children with IDs)
 */
export function mvsTreeToUINodes(tree: RawMVSTree): UINode[] {
  if (!tree.children) return [];
  return tree.children.map((node, i) => mvsNodeToUINode(node, `${i}_`));
}

/**
 * Split a `primitives` UINode into multiple nodes grouped by the `label_attachment`
 * value stored on individual `primitive` children (a UI-only extension).
 * Primitives without a per-child attachment inherit the container's value.
 * Used so a single UINode can produce multiple `.primitives()` calls in codegen.
 */
function expandPrimitivesInChildren(children: UINode[]): UINode[] {
  return children.flatMap((child) => {
    if (child.kind !== 'primitives') return [child];

    const primitiveChildren = child.children ?? [];
    const hasPerChildAttachment = primitiveChildren.some(
      (c) => c.params.label_attachment !== undefined
    );
    if (!hasPerChildAttachment) return [child];

    const containerAttachment = child.params.label_attachment as string | undefined;
    const groups = new Map<string, UINode[]>();

    for (const prim of primitiveChildren) {
      const key =
        (prim.params.label_attachment as string | undefined) ??
        containerAttachment ??
        '';
      if (!groups.has(key)) groups.set(key, []);
      const { label_attachment: _la, ...restParams } = prim.params;
      groups.get(key)!.push({ ...prim, params: restParams });
    }

    const { label_attachment: _la, ...containerRest } = child.params;
    return [...groups.entries()].map(([key, groupChildren], index) => ({
      ...child,
      // Sub-index ref so each split node gets a unique variable name in codegen.
      ref: child.ref ? `${child.ref}_${index}` : child.ref,
      params: key ? { ...containerRest, label_attachment: key } : containerRest,
      children: groupChildren,
    }));
  });
}

/**
 * Convert UINode back to raw MVS node by stripping IDs recursively.
 *
 * @param node - UINode to convert
 * @returns Raw MVS node without ID
 */
export function uiNodeToMVSNode(node: UINode): RawMVSNode {
  const result: RawMVSNode = {
    kind: node.kind,
    params: node.params,
  };

  if (node.ref) {
    result.ref = node.ref;
  }

  if (node.custom) {
    result.custom = node.custom;
  }

  if (node.children && node.children.length > 0) {
    result.children = expandPrimitivesInChildren(node.children).map(uiNodeToMVSNode);
  }

  return result;
}

/**
 * Convert UINode array to MVS Tree structure.
 *
 * @param nodes - Array of UINodes
 * @returns MVS Tree with root wrapper
 */
export function uiNodesToMVSTree(nodes: UINode[]): RawMVSTree {
  return {
    kind: 'root',
    params: {},
    children: nodes.map(uiNodeToMVSNode),
  };
}
