name: Test

on:
  push:
    paths:
      - "src/state-builder/**"
  pull_request:
    paths:
      - "src/state-builder/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test
        run: deno task test
